### PR TITLE
Refactor: New Line Characters do not render on save issue

### PR DESCRIPTION
**Pull request by tanryberdi**
- #1 issue was solve by this commit

### CODE REVIEW

**Comment by jmillerv** [comment]
Hi @tanryberdi, 

Thanks for organizing the imports. I intended for them to be sorted like that. 

You solved the newline character rendering a weird block issue when I tested it; however the output doesn't actually move the new line text down a space which we also want. 

The output still doesn't match the input like we want when I run on your branch of the code. If you can address that, I'll get this PR merged in.  

Input:

image

Ouput:
image

**Comment by tanryberdi** [comment]
ok @jmillerv, i got it, I will take a look! I think we will need refactor some others, because we need to work with text, not string one, btw, i will take a look

**Comment by jmillerv** [comment]
> ok @jmillerv, i got it, I will take a look! I think we will need refactor some others, because we need to work with text, not string one, btw, i will take a look

I agree. There will need to be refactors. I just wanted to get something out quickly and was trying to work with what the fyne library had natively.

**Comment by jmillerv** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
